const actionType = {
  GET_LIST_PRODUCT: 'GET_LIST_PRODUCT',
  GET_SEARCH_PRODUCT: 'GET_SEARCH_PRODUCT',
  FILTER_DATA: 'FILTER_DATA',
  SORT_DATA: 'SORT_DATA',
  RESET_FILTER: 'RESET_FILTER',
};

export default actionType;
